name: Validate PR title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request?.title || "";
            const regex = /^(feat|fix|chore|docs|refactor)\([a-z0-9\-]+\): .+/;
            if (!regex.test(title)) {
              core.setFailed(
                `PR title does not match required format. Example: "feat(frontend): Cool feature I implemented"\nYour title: "${title}"`
              );
            } else {
              console.log("PR title OK:", title);
            }